# za produkcisku oklonu bi kreirako zajedno s novom shcemuom i tablicama koje bi bile za produkciju

TODO: dodao bi produkcisko okruzenje i konfiguraciju za to ukljucujuci bazu i shcemu za prodkuciju posebnu sifru za prod itd..